name: Release

on:
    push:
        branches:
            - main
        paths:
            - '.changeset/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
            version: bun version
            publish: bun release
            createGithubReleases: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}